### ISSUE TITLE
03: Signup page implementation

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/frontend-authentication-module#3]
## Description
Implement the complete Signup page UI and API flows.  

## Goals
- [ ] Implement the Signup page UI
- [ ] Complete the API implementation

## Acceptance Criteria
- [ ] The signup page should work as expected.
- [ ] Page should be made responsive in all screen sizes

## Implementation Details
Angular, HTML, CSS

## Mockups / Wireframes
All the Auth flows can be viewed in [this](https://mentored.shikshalokam.org/) portal

### Product Name
SL-auth-library

### Project Name
SL-auth-library

### Organization Name:
Shikshalokam

### Domain
Education

### Tech Skills Needed:
Angular, HTML, CSS

### Mentor(s)
Amoghavarsh

### Complexity
Medium

### Category
Features

### Sub Category
Frontend, Library

**Comment by Shruti3004** [comment]
test

**Comment by abansal15** [comment]
Hello @kiranharidas187 i would like to work on this issue is this issue still open ? can you please assign it to me ?

**Comment by anjalisingh13** [comment]
@kiranharidas187  i am interested to work on this , can you assign this to me

**Comment by Sandeep0306** [comment]
Hi @kiranharidas187 I would like to work on this issue. Can you assign it to me?

**Comment by priyannshu08** [comment]
Hi @kiranharidas187 I would like to work on this issue. Can you assign it to me?

**Comment by SanjayRam07** [comment]
hello @kiranharidas187  , can I work on this issue?
Could you please assign and mentor me?

**Comment by simran142002** [comment]
@kiranharidas187  which version of angular should this be implemented in? and it should be a non standalone component right? Also we can use bootstrap right?

**Comment by simran142002** [comment]
Hello @kiranharidas187 sir, I have worked on this issue
![Uploading Screenshot from 2024-02-09 14-55-26.png…]()
![Screenshot from 2024-02-12 22-00-48](https://github.com/ELEVATE-Project/frontend-authentication-module/assets/95395832/44c8124a-4a12-444e-bc8d-b709de33f920)

[Screencast from 09-02-24 02:33:37 PM IST.webm](https://github.com/ELEVATE-Project/frontend-authentication-module/assets/95395832/6518ccf0-fdd2-4ca1-b549-7c2d455705fe)

![Screenshot from 2024-02-10 11-14-29](https://github.com/ELEVATE-Project/frontend-authentication-module/assets/95395832/1534a760-6ba2-4258-8cf0-121f82d41ec8)


[Screencast from 09-02-24 02:34:06 PM IST.webm](https://github.com/ELEVATE-Project/frontend-authentication-module/assets/95395832/b67d1204-0176-4285-a0ad-ce778156aeea)

As of now I have created an angular UI for sign up and verification page which has to be improved , I have also created an api using node js(since the api framework wasnt specified), on clicking on signup the user receives an otp (6 digit) on mail, in the verification page the user enters the otp , I have also set a timer of 40 seconds

Since there was no repository to commit too, I have created a draft pr, You can find it below

https://github.com/simran142002/SignUpPage


Sir if you could guide me further over this issue I will be able to execute it properly

**Comment by aditi-raj** [comment]
Hello @kiranharidas187 I have read and understood the issue , I would like to work on this issue. I have experience with tech stack HTML/CSS and responsive design.

**Comment by Yash-Sajwan24** [comment]
@kiranharidas187 I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by aryangandhi05** [comment]
Hello @kiranharidas187 
Sir i want to solve this issue, as i understand it, and i will give my 100% for solving this issue So please, can you assign me this?

**Comment by ishaaaa8** [comment]
Hi  @kiranharidas187 Sir , I'm interested in contributing to this issue. Could you please grant me permission to work on it? Thanks!

**Comment by adityagit-creator** [comment]
hello @kiranharidas187 I would love to solve this problem I understand the issues and I believe I have necessary skills , will for sure give my best .

**Comment by Neeharikajha** [comment]
hello @kiranharidas187 I would like to contribute in this, i have the skillset required for the same. Please assign me this so I can move forward with the development.

**Comment by PayalKumari10** [comment]
@kiranharidas187  i want to work on this issue plz assign me

**Comment by akashsingh011** [comment]
Hello, @kiranharidas187, I would like to contribute to this project. I have the required skillset for it. Please assign me to the task so I can proceed with the development.

**Comment by Abchoudhary2512** [comment]
Hello , @kiranharidas187 , i would to like to take this project. Please assign me so I can start work on development part.

**Comment by PayalKumari10** [comment]
Hello @kiranharidas187

I'll be working on implementing the Signup page UI and API flows for the SL-auth-library project by Shikshalokam. This involves:
Creating a test to assert an existing message in the network-score folder.
Ensuring the test passes Build, Cargo, and the test mentioned in Readme.md.
Implementing the signup page UI using Angular, HTML, and CSS.
Ensuring the page is responsive on all screen sizes.
Have I got the right idea? let me know if I am wrong; otherwise, Tell me so i start to working on it Thank you.
